level_0 = {
    'terrain':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\0\\level_0_terrain.csv',
    'coins':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\0\\level_0_coins.csv',
    'fg palms':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\0\\level_0_fg_palms.csv',
    'bg palms':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\0\\level_0_bg_palms.csv',
    'crates':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\0\\level_0_crates.csv',
    'enemies':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\0\\level_0_enemies.csv',
    'constraints':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\0\\level_0_constraints.csv',
    'player':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\0\\level_0_player.csv',
    'grass': 'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\0\\level_0_grass.csv',
    'node_pos': (110,400),
    'unlock':1,
    'node_graphic':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\graphics\\overworld\\0'}
level_1 = {
    'terrain':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\1\\level_1_terrain.csv',
    'coins':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\1\\level_1_coins.csv',
    'fg palms':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\1\\level_1_fg_palms.csv',
    'bg palms':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\1\\level_1_bg_palms.csv',
    'crates':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\1\\level_1_crates.csv',
    'enemies':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\1\\level_1_enemies.csv',
    'constraints':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\1\\level_1_constraints.csv',
    'player':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\1\\level_1_player.csv',
    'grass': 'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\1\\level_1_grass.csv',
    'node_pos': (400,220),
    'node_graphic':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\graphics\\overworld\\1',
    'unlock':2}
level_2 = {
    'terrain':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\2\\level_2_terrain.csv',
    'coins':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\2\\level_2_coins.csv',
    'fg palms':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\2\\level_2_fg_palms.csv',
    'bg palms':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\2\\level_2_bg_palms.csv',
    'crates':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\2\\level_2_crates.csv',
    'enemies':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\2\\level_2_enemies.csv',
    'constraints':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\2\\level_2_constraints.csv',
    'player':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\2\\level_2_player.csv',
    'grass': 'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\2\\level_2_grass.csv',
    'node_pos': (480,610),
    'node_graphic':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\graphics\\overworld\\2',
    'unlock':3}
level_3 = {
    'terrain':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\3\\level_3_terrain.csv',
    'coins':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\3\\level_3_coins.csv',
    'fg palms':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\3\\level_3_fg_palms.csv',
    'bg palms':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\3\\level_3_bg_palms.csv',
    'crates':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\3\\level_3_crates.csv',
    'enemies':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\3\\level_3_enemies.csv',
    'constraints':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\3\\level_3_constraints.csv',
    'player':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\3\\level_3_player.csv',
    'grass': 'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\3\\level_3_grass.csv',
    'node_pos': (610,350),
    'node_graphic':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\graphics\\overworld\\3',
    'unlock':4}
level_4 = {
    'terrain':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\4\\level_4_terrain.csv',
    'coins':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\4\\level_4_coins.csv',
    'fg palms':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\4\\level_4_fg_palms.csv',
    'bg palms':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\4\\level_4_bg_palms.csv',
    'crates':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\4\\level_4_crates.csv',
    'enemies':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\4\\level_4_enemies.csv',
    'constraints':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\4\\level_4_constraints.csv',
    'player':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\4\\level_4_player.csv',
    'grass': 'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\4\\level_4_grass.csv',
    'node_pos': (880,210),
    'node_graphic':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\graphics\\overworld\\4',
    'unlock':5}
level_5 = {
    'terrain':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\5\\Level_5_Terrain.csv',
    'coins':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\5\\Level_5_coins.csv',
    'fg palms':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\5\\Level_5_fg- palms.csv',
    'bg palms':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\5\\Level_5_bg_palms.csv',
    'crates':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\5\\Level_5_crates.csv',
    'enemies':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\5\\Level_5_enemies.csv',
    'constraint':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\5\\Level_5_constrain.csv',
    'player':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\5\\Level_5_player.csv',
    'grass': 'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\levelsowncreatle\\5\\Level_5_grass.csv',
    'node_pos': (1050,400),
    'node_graphic':'C:\\Users\\shaok\\source\\repos\\2-7-2023 cmp hw\\2DMariostyleplatformer\\graphics\\overworld\\5',
    'unlock':5}

levels ={
    0:level_0,
    1:level_1,
    2:level_2,
    3:level_3,
    4:level_4,
    5:level_5}
